# Final Exam Fall 2025

## Q01: Creating a List of Fruits (h0101)

Create a new Python list named `fruits`. The list must contain the following 5 string elements in this exact order:

1.  `"apple"`
2.  `"banana"`
3.  `"orange"`
4.  `"grape"`
5.  `"strawberry"`

In [ ]:
fruits = ...
fruits

## Q02. Design a function (h0110)
- call it count_elements
- with a parameter called "lst" (which means list)
- when called with a list argument, count the number of elements in the list
- return the number of elements in the list to the caller

In [2]:
def count_elements(lst):
    number_of_elements = ...
    ...

ele_count= ...

## Q03. Creating NumPy Arrays: 1D (vector) & 2D (matrix) (h0302)
Practicing array creation and attributes: 
- **dtype**,
- **ndim**, and
- **shape**.

In [ ]:
### Use the numpy arrange function to to build a one-dimensional array containing the integers 0 through 9 in order.
### assign the numpy array to a variable, call it "arr"

arr = ##### change me #####
arr

In [ ]:
### check the dimension of the array and store it to a variable dimension
### use the ndmin attribute

dimension= arr.##### change me #####
dimension

## Q04. NumPy Operations (h0303)

In [ ]:
import numpy as np
arr1 = np.arange(5)           ### 0...4
arr2 = np.arange(5, 10, 1)    ### 5...9
print("arr1 = ", arr1)
print("arr2 = ", arr2)

In [ ]:
### addition: add arr1 and arr2 and store it in a variable sum_arr

sum_arr = ##### change me #####
sum_arr

In [ ]:
### multiplication: times arr1 by arr2 and store it in a variable multiplied

multiplied= ##### change me #####
multiplied

## Q05. Pandas DataFrames (hw-pandas3.2)
- create a DataFrame from a dictionary

In [ ]:
### create a dictionary, call it fruit_price, containing 
### apple, banana, cherry as keys with lists of prices (values)

fruit_price = {
    ##### change me #####       ### the price of apple is a list [3, 2, 3]
    ##### change me #####       ### the price of banana is a list [4, 5, 4]
    ##### change me #####       ### the price of cherry is a list [5, 5, 5]
}

print(fruit_price['banana'])   ### print the price of banana

In [ ]:
### create a Pandas DataFrame using dictionary fruit_price, call it df
import pandas as pd

df = ##### change me #####        ### create the Pandas DataFrame
df

In [ ]:
### indexing and selection in DataFrame df
df01 = df[##### change me #####                 ### select the column 'banana'
df01
df02 = df[##### change me #####     ### select columns 'banana' and 'cherry'
df02
df03 = df.##### change me #####                    ### select the first row using loc
df03
df04 = df.##### change me #####                  ### select the first two rows using loc
df04
df05 = df.##### change me #####                  ### select the first row using iloc
df05
df06 = df.##### change me #####                 ### select the first two rows using iloc
df06

## Q06. SF Salaries (h05)

A salary dataset is as follows.

In [9]:
import pandas as pd
sal = pd.read_csv('./data/Salaries.csv')
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**What is the average (mean) BasePay of all employees per year (2011-2014)?**

You may need to drop some string columns here (<span style= "color:gray">'EmployeeName', 'JobTitle', 'Agency'</span>).

In [10]:
pd = sal.drop(['EmployeeName', 'JobTitle', 'Agency'], axis=1).groupby('Year').mean()
pd

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Notes,Status
Year,,,,,,,,,
2011,18080.0,63595.956517,4531.065429,3617.081926,NaN,71744.103871,71744.103871,NaN,NaN
2012,54542.5,65436.406857,5023.417824,3653.437583,26439.966967,74113.262265,100553.229232,NaN,NaN
2013,91728.5,69630.030216,5281.641980,3819.969007,23829.076572,77611.443142,101440.519714,NaN,NaN
2014,129593.0,66564.421924,5401.993737,3505.421251,24789.601756,75463.918140,100250.918884,NaN,NaN