In [6]:
# %pip install matplotlib
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
# url = "http://esapubs.org/archive/ecol/E084/093/Mammal_lifehistories_v2.txt"
# url = "https://esapubs.org/archive/ecol/E084/093/Mammal_lifehistories_v2.txt"
# data = pd.read_csv(url, sep='\t', na_values=-999.0)
# https://stackoverflow.com/questions/18039057/pandas-parser-cparsererror-error-tokenizing-data
# data = pd.read_csv(url, sep='\t', na_values=-999.0, on_bad_lines='skip')
# import codecs
# doc = codecs.open('document', 'UTF-16') 

columns = 'order	family	Genus	species	mass(g)	gestation(mo)	newborn(g)	weaning(mo)	wean mass(g)	AFR(mo)	max. life(mo)	litter size	litters/year	refs'.split()
# columns
import requests
from io import StringIO

url = "https://esapubs.org/archive/ecol/E084/093/Mammal_lifehistories_v2.txt"
pd.read_csv(url, sep='\t', header=0, na_values='-999')

,order,family,Genus,species,mass(g),gestation(mo),newborn(g),weaning(mo),wean mass(g),AFR(mo),max. life(mo),litter size,litters/year,refs
0,Artiodactyla,Antilocapridae,Antilocapra,americana,45375.0,8.13,3246.36,3.00,8900.0,13.53,142.0,1.85,1.00,"1,2,6,9,23,26,27"
1,Artiodactyla,Bovidae,Addax,nasomaculatus,182375.0,9.39,5480.00,6.50,NaN,27.27,308.0,1.00,0.99,"1,2,17,23,26"
2,Artiodactyla,Bovidae,Aepyceros,melampus,41480.0,6.35,5093.00,5.63,15900.0,16.66,213.0,1.00,0.95,"1,2,8,9,23,29"
3,Artiodactyla,Bovidae,Alcelaphus,buselaphus,150000.0,7.90,10166.67,6.50,NaN,23.02,240.0,1.00,NaN,"1,2,17,23"
4,Artiodactyla,Bovidae,Ammodorcas,clarkei,28500.0,6.80,NaN,NaN,NaN,NaN,NaN,1.00,NaN,"1,2"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1439,Xenarthra,Myrmecophagidae,Tamandua,tetradactyla,5030.0,5.22,NaN,NaN,NaN,12.00,114.0,1.00,1.35,"1,2,3,13,16"
1440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
# plt.plot(data['mass(g)'], data['gestation(mo)'])
type(data)

pandas.core.frame.DataFrame

In [9]:
data.describe()

       <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
count                                                  55
unique                                                 54
top                                                </div>
freq                                                    2

In [10]:
cat = ['|\\---/|', '| o_o |', ' \\_^_/' ]
for i in cat:
    print(i)

|\---/|
| o_o |
 \_^_/