# Managing Datasets

In [45]:
# if you have not installed pandas through the command line
# do so by opening a new command line tab/window, then
# activate the virtual environment, and issue "pip install pandas"
# or, you may do "%pip install pandas" in a Jupyter notebook.
# do remember to comment out the installation line afterwards
# so that it would not run every time you run the cell

# we also need NumPy sometimes for processing data as it's the foundation of Pandas

# %pip install pandas
# %pip install numpy
import numpy as np
import pandas as pd

## Accessing Dataset Files

To access datasets (usually files), you can either:

- set a path variable to the data folder, which will be easier in the long run; or
- write path (full or relative) and file names as arguments

You are learning these basic operations now and will probably just use **relative path** in the future.

When importing datasets, some path information are good to know:

1. **Full paths**:

   - **macOS** (and Linux): A full/absolute path starts with "`/`" (the "root" directory) or you can use "`~`" to start with the user's home directory (e.g., data_path = "/Users/<user>`/`workspace/data/" == "`~`/workspace/data/").

   - **Windows**: A full path includes a drive letter and backslashes (`\`) for path separator (e.g. data_path = "`C:`\Users\<user>\workspace\dsm\data\") though forward slashes usually work as well.

2. **Relative paths**: Usually it's just easier to use a relative path to access the data folders (e.g., `../../data/`).

3. Current working directory (CWD/PWD): To know your Current/Present Working Directory (this notebook's location), use `os.getcwd()` or `%pwd`.
   
4. Home directory: To write portable code across OSs, we prefer `os.path.expanduser`, which can resolve the directory passed (e.g., `~`) for us to use.

5. Join paths: This is used to join the path variable with the paths/filenames instead of hardcoding separators and literals. For example, `os.path.join( )` to join a path and a dataset file.

As an example, the `os.getcwd()` function will give us the full path of the notebook you are working on, which can be critical when using relative paths.

In [46]:
import os   ### os is a standard library module for interacting with the OS.
CWD = os.getcwd()
CWD  # print current working directory

'/Users/tcn85/workspace/dsm/data'

### Getting home directory

You can hardcode the path of your home directory (where you are when you start your terminal), but it is suggested to use `os.path.expanduser('~')` in Python environment, which works in different operating systems.

For Windows users:

In [47]:
### if you are using macOS or Linux, you can use "~" to represent your home directory
### in Windows, you need to either use the full path (e.g., "C:/Users/[user]/...")
### or, you can use os.path.expanduser('~') to get your home directory in a cross-platform way
# we want to access the data directory so that we can read data files
# without specifying the full path
# os.path.expanduser can be used to
# you can expand ~ to the full user home path and keep the path as a string
# in the terminal/shell, it's $HOME but in Python it's os.path.expanduser('~')
home_dir = os.path.expanduser('~')

### Note that we'll use this variable later to construct the full path to the data directory:
data_path = os.path.join(home_dir, "workspace", "dsm", "data")

In macOS or Linux:

### Setting full path

- Setting paths is optional, but it comes in handy when you use the same data folder over time.
- you can use a relative path or a full/absolute path to achieve this.

Following the steps:

1.  import **os.path**:

    `import os.path as path`

2.  At the terminal, find and save the **full path**:

````{tab-set}

```{tab-item} **Windows**:
      PS C:\Users\[user]\workspace\dsm> cd data
      PS C:\Users\[user]\workspace\dsm\data> pwd   ### pwd: present working directory
      Path
      ----
      C:\Users\[user]\workspace\dsm\data

   Then, copy the path to your notebook:

      data_path = 'C:\Users\[user]\workspace\dsm\data'`
```

```{tab-item} **macOS**:

      (.venv) [uer]@[host]ː~/workspace/dsm$ cd data
      (.venv) [user]@[host]ː~/workspace/dsm/data$ pwd
      /Users/[user]/workspace/dsm/data

   Copy the full path to the notebook, then:

      data_path = '/Users/[user]/workspace/dsm/data'
```
````


3.  **Join path**:

    `data = path.join(data_path, "data.csv")` ### add the file with path.join( )

### Using relative path

To access files in another folder in the project, you need to provide a path in your code. For example, if you are in the 02-YOU-ARE-HERE-**02**.ipynb, and you need to read the **example** file in the **data** directory, you need to say:

`df = pd.read_csv('../../data/example')`

- Explanation: Here, `..` means "go up one level in the directory tree structure." So, you are working with the 02.ipynb file, and you need to access the file `example`. You have to point to Jupyter to go up one level from inside the `folder` folder to the `notebooks` level, then one more level up to the project folder (dsm) level, then go into the `data` folder to find `example`.

<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'Windows')">Windows</button>
  <button class="tablinks" onclick="openTab(event, 'macOS')">macOS</button>
</div>

<div id="Windows" class="tabcontent">
  <pre><code>
(.venv) PS C:\Users\[user]\workspace\dsm> tree
Folder PATH listing
Volume serial number is 420C-3FF4
C:.
├───.ipynb_checkpoints
├───.venv
├── data
│   ├── actors.csv
│   ├── example
│   └── wine.csv
├── notebooks
│   ├── 02-np-YOU-ARE-HERE-01.ipynb
│   └── folder
│       └── 02-YOU-ARE-HERE-02.ipynb
  </code></pre>
</div>

<div id="macOS" class="tabcontent" style="display:none">
  <pre><code>
  [user]@[host]ː~/workspace/dsm$ tree
.
├── data
│   ├── actors.csv
│   ├── example
│   └── wine.csv
├── notebooks
│   ├── 02-np-YOU-ARE-HERE-01.ipynb
│   └── folder
│       └── 02-YOU-ARE-HERE-02.ipynb
  </code></pre>
</div>

<script>
function openTab(evt, tabName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>

## Reading Dataset Files

Now let us read the dataset file using `pd.read_csv( )`. You may read the data file directly or and open it as a file and save it a variable so you can manipulate the data file.

In [48]:
# now we can read the data file using pandas
# this is one way to do it
home = os.path.expanduser('~')
data_path = os.path.join(home, 'workspace', 'dsm', 'data')
data = os.path.join(data_path, 'data.csv')
with open(data) as f:  # open the file for reading and assign the file object variable f
    df = pd.read_csv(f)  # read the csv file into a DataFrame
df.head()  # display the first 5 rows of the DataFrame

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

In [49]:
# just to show the path variables we used
data_path

'/Users/tcn85/workspace/dsm/data'

In summary, there are different ways of reading your datasets:

#### Use relative path

In [50]:
# another way to do it is to use relative path
# ../../data/data.csv
data = ("../../data/data.csv")
df = pd.read_csv(data)

FileNotFoundError: [Errno 2] No such file or directory: '../../data/data.csv'

#### Path variable & filename

In [ ]:
df = pd.read_csv(data_path + "/data.csv")

#### Use `path.join`

In [ ]:
data = os.path.join(data_path, "data.csv")
df = pd.read_csv(data)

#### Use with statement
When you need to manipulate the file.

In [ ]:
with open(data_path+"/data.csv") as f:
    df = pd.read_csv(f)

#### change dir
Alternatively, change directory into the data folder and read the data from there.

In [ ]:
os.chdir(data_path)
df = pd.read_csv("data.csv")
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10