In [69]:
import pandas as pd
import numpy as np
import os.path as path
data_path = "../../data/"
data = path.join(data_path, "data.csv")
# with open(data) as f:
#     df = pd.read_csv(f)
df = pd.read_csv(data)

In [70]:
df.head()

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

In [71]:
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

In [72]:
df.dtypes
# df.dtypes
# float(df['Duration'])

Duration    object
Pulse       object
Maxpulse    object
Calories    object
dtype: object

In [75]:
### convert Duration column to numeric, invalid parsing will become NaN
### IMPORTANT: errors='coerce' will replace non-convertible values with NaN
df['Duration'] = pd.to_numeric(df['Duration'], errors='coerce')
print(df.dtypes)

Duration    float64
Pulse        object
Maxpulse     object
Calories     object
dtype: object

In [77]:
df = pd.DataFrame({col: pd.to_numeric(df[col], errors='coerce') for col in df.columns})

In [78]:
df.corr()

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922721
Pulse    -0.155408  1.000000  0.786535  0.025120
Maxpulse  0.009403  0.786535  1.000000  0.203814
Calories  0.922721  0.025120  0.203814  1.000000